name: Auto Update Stocks

on:
  schedule:
    # —— Daylight Time (EDT, ~Mar–Nov): 09:30–16:30 ET == 13:30–20:30 UTC
    - cron: '30 13-20 * * 1-5'
    # Extra pass near close: 16:45 ET == 20:45 UTC
    - cron: '45 20 * * 1-5'

    # —— Standard Time (EST, ~Nov–Mar): 09:30–16:30 ET == 14:30–21:30 UTC
    - cron: '30 14-21 * * 1-5'
    # Extra pass near close: 16:45 ET == 21:45 UTC
    - cron: '45 21 * * 1-5'
  workflow_dispatch: {}

permissions:
  contents: write

concurrency:
  group: auto-update-stocks
  cancel-in-progress: true

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install deps
        run: pip install pandas requests pytz

      - name: Run stock update
        run: python Automation.py
        env:
          POLYGON_API_KEY: ${{ secrets.POLYGON_API_KEY }}
          FORCE_RUN: ${{ github.event_name == 'workflow_dispatch' }}

      - name: Commit and Push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add stocks.csv
          git commit -m "📈 Auto-update stocks.csv from workflow" || echo "No changes to commit"
          git push

      - name: Send Trade Summary Email
        run: python send_email.py
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
          EMAIL_SMTP_HOST: ${{ secrets.EMAIL_SMTP_HOST }}
          EMAIL_SMTP_PORT: ${{ secrets.EMAIL_SMTP_PORT }}
